input_field_names:
  - japanese
output_field_name: sentence
prompt_template: "Generate a short example sentence for the following japanese word: {japanese}. Only return the example sentence, no translation or other tokens. Wrap the exemplified japanese word in '<span style='background-color: #897099'>'. For example: japanese word: '試合[しあい]' -> 彼はサッカーの<span style='background-color: #897099'>試合</span>に勝った。"
do_overwrite_output: false
